---
sidebar: sidebar 
permalink: setup-email-upgrade-health-checker.html 
keywords: upgrade, health, checker 
summary: Upgrade Health Checkerのレポートを受信するためのEメールを設定できます。 
---
= アップグレードヘルスチェッカーレポートをメールで受信
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Upgrade Health Checker は、レポートを直接メールボックスに送信できます。この機能は、config.yaml ファイルまたはコマンドライン引数で有効にできます。有効化すると、Upgrade Health Checker は生成されたレポート（HTML、Excel、または JSON 形式）を SMTP サーバー経由で1人以上の受信者に送信します。無効にすると、レポートは送信されません。レポートの生成が失敗し、メール送信が有効になっている場合、Upgrade Health Checker はログファイルを設定済みの受信者にメールで送信します。



[[configure-using-the-config-yaml-file]]
== config.yamlファイルを使用して設定します

config.yaml ファイルでメール設定を構成するには、メールレポートを有効にし、SMTP サーバーの詳細を追加し、受信者アドレスとレポート形式を指定します。

. config.yamlファイルでメールレポートを有効にします。
+
[listing]
----
# Email Report Configuration
EMAIL:
  ENABLED: true
----
. SMTP設定、送信者情報、件名を追加します：
+
[listing]
----
# SMTP Server Configuration
EMAIL:
  ENABLED: true
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  SMTP:
    HOST: "smtp.example.com"
    PORT: [<port-number>]
----
. 受信者のメールアドレスを追加し、システムがメールで送信するレポートの形式（HTML、EXCEL、JSON、またはすべてなど）を設定します。認証と暗号化も利用できます。
+
[listing]
----
# Recipient Email Addresses, report formats
EMAIL:
  ENABLED: true
  TO: <recipient>
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  RECIPIENTS: "user1@example.com, user2@example.com"
  REPORT_FORMATS: "HTML,EXCEL,JSON"   # valid values: HTML, EXCEL, JSON or ALL
  SMTP:
    HOST: "smtp.example.com"
    PORT: [PORT]
    USE_SMTP_AUTH: true
    USE_TLS: true
    USE_SSL: true
    USERNAME: "user@example.com"
    PASSWORD: "********"
----




[[configure-using-command-line-arguments]]
== コマンドライン引数を使用して設定する

コマンドライン引数を使用して基本的なメール設定を構成し、レポートの有効化、受信者の指定、レポート形式の選択を行うことができます。

. コマンドライン引数を使用してメールレポートを有効にする：
+
[listing]
----
./uhc --email-enabled=true
----
. 受信者のメールアドレスを入力してください：
+
[listing]
----
./uhc --email-recipients="user1@example.com, user2@example.com"
----
. メールで送信するレポート形式（HTML、EXCEL、JSONなど）を設定します：
+
[listing]
----
./uhc --email-report-formats=HTML,EXCEL,JSON
----


[NOTE]
====
以下の3つの属性は、コマンドライン引数またはconfig.yamlファイルを使用して設定できます。残りの属性はすべてconfig.yamlファイルでのみ設定できます：

* Eメールが有効
* E メール受信者
* Eメールレポート形式


コマンドライン引数はconfig.yamlファイルの値を上書きすることに注意してください。

次に例を示します。

[listing]
----
./uhc \
  --email-enabled=true
  --email-recipients="user1@example.com, user2@example.com" \
  --email-report-formats=HTML,EXCEL,JSON \
----
[listing]
----
EMAIL:
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  SMTP:
    HOST: "smtp.example.com"
    PORT: [PORT]
----
====