---
sidebar: sidebar 
permalink: setup-email-upgrade-health-checker.html 
keywords: upgrade, health, checker 
summary: Upgrade Health Checkerのレポートを受信するためのEメールを設定できます。 
---
= アップグレードヘルスチェッカーレポートをメールで受信
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Upgrade Health Checkerにメールを統合することで、レポートをメールで受信できます。この機能は、config.yamlファイルまたはコマンドライン引数によって有効にできます。有効化すると、Upgrade Health Checkerは生成されたレポート（HTML、Excel、またはJSON形式）をSMTPサーバーを使用して、設定済みの1つ以上の受信者に送信します。この機能が無効になっている場合、レポートは送信されません。レポート生成が失敗し、メール送信が有効になっている場合、ログファイルは設定された受信者に送信されます。



== config.yamlファイルを使用して設定します

. config.yamlファイルでメールレポートを有効にします。
+
[listing]
----
# Email Report Configuration
EMAIL:
  ENABLED: true
----
. 送信者の詳細と件名を含むSMTP設定を入力してください：
+
[listing]
----
# SMTP Server Configuration
EMAIL:
  ENABLED: true
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  SMTP:
    HOST: "smtp.example.com"
    PORT: [<port-number>]
----
. 受信者のメールアドレスを指定し、メールで送信するレポート形式（HTML、EXCEL、JSON、ALLなど）を設定します：
+
[listing]
----
# Recipient Email Addresses, report formats
EMAIL:
  ENABLED: true
  TO: <recipient>
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  RECIPIENTS: "user1@example.com, user2@example.com"
  REPORT_FORMATS: "HTML,EXCEL,JSON"   # valid values: HTML, EXCEL, JSON or ALL
  SMTP:
    HOST: "smtp.example.com"
    PORT: [PORT]
----




== コマンドライン引数を使用して設定する

. コマンドライン引数を使用してメールレポートを有効にする：
+
[listing]
----
./uhc --email-enabled=true
----
. 受信者のメールアドレスを入力してください：
+
[listing]
----
./uhc --email-recipients="user1@example.com, user2@example.com"
----
. メールで送信するレポート形式（HTML、EXCEL、JSONなど）を設定します：
+
[listing]
----
./uhc --email-report-formats=HTML,EXCEL,JSON
----


[NOTE]
====
以下の3つの属性は、コマンドライン引数とconfig.yamlファイルの両方を使用して設定できます。残りの属性はconfig.yamlファイルでのみ設定可能です：

* Eメールが有効
* E メール受信者
* Eメールレポート形式


コマンドライン引数が指定された場合、config.yamlファイルの値が上書きされることに注意してください。

次に例を示します。

[listing]
----
./uhc \
  --email-enabled=true
  --email-recipients="user1@example.com, user2@example.com" \
  --email-report-formats=HTML,EXCEL,JSON \
----
[listing]
----
EMAIL:
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  SMTP:
    HOST: "smtp.example.com"
    PORT: [PORT]
----
====