---
sidebar: sidebarU 
permalink: whats-new.html 
keywords: upgrade, health, checker, whats new, release, notes 
summary: このドキュメントサイトの新機能について学習します。 
---
= Upgrade Health Checker の新機能
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Upgrade Health Checker（UHC）の新機能について説明します。link:https://console.netapp.com/automationHub["NetApp Console自動化ハブ"^]でUpgrade Health Checkerタイルに移動し、最新のUpgrade Health Checkerダウンロードファイルを表示すると、追加の機能強化情報を確認できます。



== 2026年6月11日

今回のアップグレードヘルスチェッカーのドキュメント更新には、以下の機能が含まれています。

* UHCは、レポートを受信トレイに直接配信することをサポートしています。
+
link:setup-email-upgrade-health-checker.html["アップグレードヘルスチェッカーレポートをメールで受信"].

*  `--dashboard`パラメータを導入します。このパラメータは、クラスタに接続することなく、 `<runs>/dashboard/index.html`の既存の実行からダッシュボードを再生成します。最近アクセスされたすべてのクラスタの健全性ステータスの概要を提供します。
+
link:dashboard-upgrade-health-checker.html["Health Checkerダッシュボードのアップグレード"]、link:upgrade-health-checker-input-parameters.html#dashboard["ダッシュボードパラメータ"]。

* 新たに「メンテナンス」「トラブルシューティング」「よくある質問」セクションを追加しました。
+
** アップグレードヘルスチェッカーを常に良好な状態に保つには、定期的にアップデートを確認し、ログを監視して繰り返し発生する問題がないかを確認し、ツールがご使用の環境に合わせて正しく構成されていることを確認してください。
+
link:maintain-upgrade-health-checker.html["アップグレードヘルスチェッカーのメンテナンス"].

** Upgrade Health Checkerの一般的な問題のトラブルシューティングを行い、ONTAPアップグレード計画をブロックする可能性のあるエラーを解決します。
+
link:troubleshoot-upgrade-health-checker.html["アップグレードヘルスチェッカーのトラブルシューティング"].

** Upgrade Health Checker に関するよくある質問（FAQ）。
+
link:faq-upgrade-health-checker.html["Upgrade Health Checkerに関するFAQ"].







== 2026年4月15日

今回のアップグレードヘルスチェッカーのドキュメント更新には、以下の機能が含まれています。

* UHC が自動更新機能を動作させるには、新しいエンドポイント (+https://api.activeiq.netapp.com+) へのアクセスが必要です。
+
link:set-up-upgrade-health-checker.html["Upgrade Health Checkerをダウンロードしてセットアップする"]。

* UHCは、HTML（人間が読める形式）およびJSON（機械が読める形式）を補完する新しいレポート形式（.XLSX - 人間が編集可能な形式）を提供するようになりました。
+
link:generate-report-upgrade-health-checker.html["ONTAPアップグレードレポートを生成する"]。

+
link:automate-report-upgrade-health-checker.html["Upgrade Health Checkerでアップグレード計画の生成を自動化"]。





== 2026年2月13日

Upgrade Health Checkerは、包括的なオンサイトレポートを生成する新しいソリューションを提供し、ONTAPアップグレードを成功させることができます。既存の自動化およびオーケストレーションフレームワークと併用することで、単一または複数のクラスタをアップグレードする際の効率を高めることができます。Upgrade Health Checkerは、ONTAP 9.11.1以降へのアップグレードをサポートします。

link:learn-about-upgrade-health-checker.html["Upgrade Health Checkerの詳細"]。
